plugin:
  name: custom-data-type-georef
  version: 1.25
  url: https://github.com/programmfabrik/easydb-custom-data-type-georef
  displayname:
    de-DE: georef-Verknüpfung
    en-US: georef-Referencing
  info:
    de-DE: Ermöglicht Georeferenzierungen auf einer Karte im geoJSON-Format.
    en-US: Enables georeferencing on a map in geoJSON format.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-georef.js
    l10n: l10n/
    css: custom-data-type-georef.css
custom_types:
  georef:
    update:
      script: build/updater/georef-update.js
      timeout: 60
      batch_size: 100
      interval_base_config: update_interval_georef.days    
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: mapbox_access_token
          parameters:
            value:
              type: text
base_config:
  - name: update_interval_georef
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
